# -*- coding: utf-8 -*-
"""Project 316.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tzRB0YBYWDblUzCjYWD-OBbB9rfeunQQ
"""

import nltk
nltk.download('popular')
nltk.download('wordnet')

import pandas as pd
import re
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import hstack, csr_matrix

from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, hamming_loss, f1_score
from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import MultinomialNB
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import classification_report, f1_score, accuracy_score,hamming_loss

from sklearn.ensemble import RandomForestClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import classification_report, f1_score, hamming_loss

from sklearn.svm import LinearSVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import classification_report, hamming_loss, f1_score

from sklearn.neural_network import MLPClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import classification_report, hamming_loss, f1_score

def nlbse_cleaner(text):
    text = text.lower()
    # Replace periods in Latin contractions to prevent sentence splitting errors
    text = re.sub(r'\b(e\.g\.|i\.e\.|etc\.)', lambda x: x.group(0).replace('.', ''), text)
    # Keep only safe technical characters
    text = re.sub(r'[^a-z0-9,. @#&^%!?\n]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Load Parquet
splits = {'java_train': 'data/java_train-00000-of-00001.parquet', 'java_test': 'data/java_test-00000-of-00001.parquet', 'python_train': 'data/python_train-00000-of-00001.parquet', 'python_test': 'data/python_test-00000-of-00001.parquet', 'pharo_train': 'data/pharo_train-00000-of-00001.parquet', 'pharo_test': 'data/pharo_test-00000-of-00001.parquet'}
df = pd.read_parquet("hf://datasets/NLBSE/nlbse25-code-comment-classification/" + splits["java_train"])

# Clean Text
df['cleaned_sentence'] = df['comment_sentence'].apply(nlbse_cleaner)

# Label Processing
df['y_matrix'] = df['labels'].apply(lambda x: np.array(x) if isinstance(x, (list, np.ndarray)) else np.array(eval(x)))

df[['cleaned_sentence', 'y_matrix']].to_parquet('cleaned_ready_for_features.parquet')

# Generate TF-IDF Features
tfidf = TfidfVectorizer(ngram_range=(1, 3), max_features=35000, stop_words='english')
X_tfidf = tfidf.fit_transform(df['cleaned_sentence'])

# Extract Manual Stylometric Features
def get_manual_features(dataframe):
    # Length of original sentence
    length = dataframe['comment_sentence'].str.len().values
    # Count of digits
    digit_count = dataframe['comment_sentence'].apply(lambda x: sum(c.isdigit() for c in x)).values
    # Count of special characters (@, #, !, etc.)
    special_char_count = dataframe['comment_sentence'].apply(lambda x: sum(not c.isalnum() for c in x)).values

    return np.column_stack((length, digit_count, special_char_count))

manual_features = get_manual_features(df)

# Combine both streams into the Final Matrix
# Convert manual features to sparse format to match TF-IDF
manual_features_sparse = csr_matrix(manual_features)

# This creates your final training data X
X_final = hstack([X_tfidf, manual_features_sparse])

print(f"Feature extraction successful. Matrix shape: {X_final.shape}")

# Prepare the y_matrix from your dataframe
# We must convert the list-like labels into a 2D NumPy array
y_matrix = np.stack(df['labels'].values)

# Split the hybrid feature matrix (X_final) and the newly defined y_matrix
X_train, X_test, y_train, y_test = train_test_split(X_final, y_matrix, test_size=0.2, random_state=42)

# Define and Initialize the Model
# 'class_weight=balanced' is key for the imbalanced labels we found
model = OneVsRestClassifier(LogisticRegression(max_iter=1000, class_weight='balanced'))

# Train the Model
print("Training the Logistic Regression model...")
model.fit(X_train, y_train)

# Generate Predictions
y_pred = model.predict(X_test)

# Final Report
hl = hamming_loss(y_test, y_pred)
micro_f1 = f1_score(y_test, y_pred, average='micro')

report = classification_report(
    y_test,
    y_pred,
    target_names=[f"Label_{i}" for i in range(y_test.shape[1])],
    zero_division=0
)

print(f"\n--- Evaluation Results ---")
print(f"Hamming Loss: {hl:.4f}")
print(f"Micro-Averaged F1 Score: {micro_f1:.4f}")
print("\n--- Detailed Report per Label ---")

# 1. Raw probability scores (0.0 to 1.0) instead of hard 0/1
y_probs = model.predict_proba(X_test)

# 2. Custom thresholds
custom_thresholds = [0.55, 0.45, 0.50, 0.45, 0.40, 0.45, 0.4]

y_pred_tuned = np.zeros(y_probs.shape)
for i in range(len(custom_thresholds)):
    y_pred_tuned[:, i] = (y_probs[:, i] >= custom_thresholds[i]).astype(int)

# 3. Final Comparison
print(f"Tuned Micro-F1: {f1_score(y_test, y_pred_tuned, average='micro'):.4f}")
print("\n--- Optimized Multi-Label Report ---")
print(classification_report(y_test, y_pred_tuned, zero_division=0))

from sklearn.naive_bayes import ComplementNB

# Model 2: Complement Naive Bayes (Better for imbalanced text datasets)
# ComplementNB is specifically designed to handle imbalanced classes
nb_model = OneVsRestClassifier(ComplementNB())

print("Training Complement Naive Bayes...")

# Train model
nb_model.fit(X_train, y_train)

# Predict
y_pred_nb = nb_model.predict(X_test)

# Evaluation
nb_hl = hamming_loss(y_test, y_pred_nb)
nb_f1 = f1_score(y_test, y_pred_nb, average='micro')

print("\n--- Naive Bayes Evaluation Results ---")
print(f"Hamming Loss: {nb_hl:.4f}")
print(f"Micro-Averaged F1 Score: {nb_f1:.4f}")

print("\n--- Detailed Multi-Label Report (Naive Bayes) ---")
print(classification_report(y_test, y_pred_nb, zero_division=0))

# 3. Random Forest Model
# We use OneVsRestClassifier for the multi-label task
# 'n_estimators=100' provides a robust ensemble of trees
# 'class_weight=balanced' is critical for handling the imbalanced labels identified in the sources
rf_model = OneVsRestClassifier(RandomForestClassifier(n_estimators=100, class_weight='balanced', n_jobs=-1, random_state=42))

# 2. Train the Model
print("Training Random Forest on hybrid features...")
rf_model.fit(X_train, y_train)

# 3. Generate Predictions
y_pred_rf = rf_model.predict(X_test)

# 4. Empirical Evaluation
hl_rf = hamming_loss(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf, average='micro')

print(f"\n--- Random Forest Evaluation Results ---")
print(f"Hamming Loss: {hl_rf:.4f}")
print(f"Micro-Averaged F1 Score: {f1_rf:.4f}")
print("\n--- Detailed Multi-Label Report (Random Forest) ---")
print(classification_report(y_test,
    y_pred_rf,
    target_names=[f"Label_{i}" for i in range(y_test.shape[1])],zero_division=0))

from sklearn.svm import LinearSVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import classification_report, hamming_loss, f1_score
from sklearn.preprocessing import MaxAbsScaler

# 1. Scale features to help SVM convergence
# MaxAbsScaler is used because it maintains the sparsity of X_train
scaler = MaxAbsScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 2. Define and Initialize the Linear SVM Model
# Increased max_iter and used scaling for better convergence
svm_classifier = OneVsRestClassifier(
    LinearSVC(class_weight='balanced', max_iter=10000, random_state=42, dual=True)
)

# 3. Train the Model
print("Training Linear SVM on scaled features...")
svm_classifier.fit(X_train_scaled, y_train)

# 4. Generate Predictions
y_pred_svm = svm_classifier.predict(X_test_scaled)

# 5. Evaluation
svm_hl = hamming_loss(y_test, y_pred_svm)
svm_f1 = f1_score(y_test, y_pred_svm, average='micro')

print(f"\n--- SVM Evaluation Results ---")
print(f"Hamming Loss: {svm_hl:.4f}")
print(f"Micro-Averaged F1 Score: {svm_f1:.4f}")
print("\n--- Detailed Multi-Label Report (SVM) ---")
print(classification_report(y_test, y_pred_svm, zero_division=0))

# 5. Initialize the MLP (Neural Network)
# 'hidden_layer_sizes' defines the architecture (100 neurons in one layer)
# 'max_iter' corresponds to the number of epochs (passes over the data)
mlp_model = OneVsRestClassifier(MLPClassifier(
    hidden_layer_sizes=(100,),
    activation='relu',
    solver='adam',
    max_iter=100,
    early_stopping=True,
    validation_fraction=0.1,
    random_state=42,
    verbose=False # Set to True to see the 'epochs'/loss in real-time
))

# 2. Train the Model
print("Training Multi-Layer Perceptron...")
mlp_model.fit(X_train, y_train)

# 3. Generate Predictions
y_pred_mlp = mlp_model.predict(X_test)

# 4. Evaluation
mlp_hl = hamming_loss(y_test, y_pred_mlp)
mlp_f1 = f1_score(y_test, y_pred_mlp, average='micro')

print(f"\n--- MLP Evaluation Results ---")
print(f"Hamming Loss: {mlp_hl:.4f}")
print(f"Micro-Averaged F1 Score: {mlp_f1:.4f}")
print("\n--- Detailed Multi-Label Report (MLP) ---")
print(classification_report(y_test, y_pred_mlp, zero_division=0))

# Split the original sentences using the same random seed
X_train_text, X_test_text, y_train, y_test = train_test_split(
    df['comment_sentence'],
    y_matrix,
    test_size=0.2,
    random_state=42
)

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from scipy.sparse import hstack, csr_matrix
import numpy as np

# 1. Initialize Bag-of-Words Vectorizer
bow_vectorizer = CountVectorizer(ngram_range=(1, 3))

# 2. Transform the cleaned code snippets
X_bow_text = bow_vectorizer.fit_transform(df['cleaned_sentence'])

# 3. Memory-efficient Combine: Use scipy.sparse.hstack instead of np.hstack
# This avoids converting the sparse matrix to a massive dense array
manual_features_sparse = csr_matrix(manual_features)
X_bow_final = hstack([X_bow_text, manual_features_sparse])

# 4. Split
X_train_bow, X_test_bow, y_train, y_test = train_test_split(
    X_bow_final, y_matrix, test_size=0.2, random_state=42
)

print(f"BoW Hybrid Matrix created efficiently. Training shape: {X_train_bow.shape}")

from sklearn.ensemble import RandomForestClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import classification_report, f1_score, hamming_loss

# Initialize RF with balanced weights for the noisy/imbalanced rule-based labels
rf_bow_model = OneVsRestClassifier(RandomForestClassifier(n_estimators=100, class_weight='balanced', n_jobs=-1, random_state=42))

print("Training Random Forest (BoW Baseline)...")
rf_bow_model.fit(X_train_bow, y_train)

# Predictions and Evaluation
y_pred_rf_bow = rf_bow_model.predict(X_test_bow)

print(f"\n--- Random Forest (BoW) Results ---")
print(f"Hamming Loss: {hamming_loss(y_test, y_pred_rf_bow):.4f}")
print(f"Micro-F1 Score: {f1_score(y_test, y_pred_rf_bow, average='micro'):.4f}")

from sklearn.svm import LinearSVC
from sklearn.preprocessing import MaxAbsScaler

# Scaling is essential for SVM convergence, especially with hybrid features
scaler = MaxAbsScaler()
X_train_bow_scaled = scaler.fit_transform(X_train_bow)
X_test_bow_scaled = scaler.transform(X_test_bow)

# Initialize Linear SVM with a more robust approach
# MaxAbsScaler keeps the data sparse while helping convergence
svm_bow_model = OneVsRestClassifier(LinearSVC(class_weight='balanced', random_state=42, max_iter=10000, dual=True))

print("Training SVM (BoW Baseline) with scaled features...")
svm_bow_model.fit(X_train_bow_scaled, y_train)

# Predictions and Evaluation
y_pred_svm_bow = svm_bow_model.predict(X_test_bow_scaled)

print(f"\n--- SVM (BoW) Results ---")
print(f"Hamming Loss: {hamming_loss(y_test, y_pred_svm_bow):.4f}")
print(f"Micro-F1 Score: {f1_score(y_test, y_pred_svm_bow, average='micro'):.4f}")

import pandas as pd

# Collect metrics from all models
results_data = {
    'Model': ['Logistic Regression (Tuned)', 'Complement Naive Bayes', 'Random Forest', 'Linear SVM', 'MLP (Neural Net)', 'RF (BoW Baseline)', 'SVM (BoW Baseline)'],
    'Micro-F1': [
        f1_score(y_test, y_pred_tuned, average='micro'),
        nb_f1,
        f1_rf,
        svm_f1,
        mlp_f1,
        f1_score(y_test, y_pred_rf_bow, average='micro'),
        f1_score(y_test, y_pred_svm_bow, average='micro')
    ],
    'Hamming Loss': [
        hamming_loss(y_test, y_pred_tuned),
        nb_hl,
        hl_rf,
        svm_hl,
        mlp_hl,
        hamming_loss(y_test, y_pred_rf_bow),
        hamming_loss(y_test, y_pred_svm_bow)
    ]
}

comparison_df = pd.DataFrame(results_data).sort_values(by='Micro-F1', ascending=False)

print("--- Model Performance Comparison ---")
display(comparison_df)

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Model Comparison Chart
plt.figure(figsize=(12, 6))
sns.barplot(x='Micro-F1', y='Model', data=comparison_df, palette='magma', hue='Model', legend=False)
plt.title('Model Performance Comparison (Micro-F1 Score)')
plt.xlim(0, 1.0)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

from sklearn.metrics import f1_score

# 2. Per-Label Comparison (Using Random Forest as it performed well)
# Calculate F1 for each label individually
f1_per_label = f1_score(y_test, y_pred_rf, average=None)
label_names = [f'Label_{i}' for i in range(len(f1_per_label))]

plt.figure(figsize=(10, 5))
sns.barplot(x=label_names, y=f1_per_label, palette='coolwarm', hue=label_names, legend=False)
plt.title('F1 Score per Label (Random Forest Model)')
plt.ylabel('F1 Score')
plt.ylim(0, 1.1)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

def classify_quality(prediction_row):
    # Mapping logic
    # GOOD: Summary (0), Usage (3), Rationale (4)
    if prediction_row[0] == 1 or prediction_row[3] == 1 or prediction_row[4] == 1:
        return "GOOD: Informative"

    # QUESTIONABLE: Warning (5), Ownership (1), Expand (2)
    elif prediction_row[5] == 1 or prediction_row[1] == 1 or prediction_row[2] == 1:
        return "QUESTIONABLE: High-Risk"

    # BAD: Task (6)
    elif prediction_row[6] == 1:
        return "BAD: Technical Debt"

    else:
        return "UNCATEGORIZED"

# Create the final audit dataframe
audit_report = pd.DataFrame({
    'Comment_Text': X_test_text.values,
    'Quality_Rating': [classify_quality(row) for row in y_pred_tuned]
})

# Display a sample of the results
print(audit_report.head(35))

import matplotlib.pyplot as plt

# Count the ratings
quality_counts = audit_report['Quality_Rating'].value_counts()

# Plot it
plt.figure(figsize=(10,6))
quality_counts.plot(kind='pie', autopct='%1.1f%%', colors=['#4CAF50', '#FFC107', '#F44336', '#9E9E9E'])
plt.title("Distribution of Code Comment Quality")
plt.ylabel("")
plt.show()

# End prompt FUNCTION — RANDOM FOREST + BAG OF WORDS

from scipy.sparse import csr_matrix, hstack
import numpy as np

def audit_code_comment(raw_comment):

    # 1. MANUAL STYLOMETRIC FEATURES

    length = len(raw_comment)

    digit_count = sum(c.isdigit() for c in raw_comment)

    special_char_count = sum(
        not c.isalnum() and not c.isspace()
        for c in raw_comment
    )

    manual_features = np.array([
        [length, digit_count, special_char_count]
    ])

    manual_features_sparse = csr_matrix(manual_features)

    # 2. BAG-OF-WORDS FEATURE EXTRACTION

    text_features = bow_vectorizer.transform([raw_comment])

    # 3. HYBRID FEATURE FUSION

    final_input = hstack([
        text_features,
      manual_features_sparse
    ])

    # 4. MODEL PREDICTION

    prediction = rf_bow_model.predict(final_input)

    prediction_row = prediction[0]


    # 5. LABEL MAPPING

    label_names = [
        "SUMMARY",
        "OWNERSHIP",
        "EXPAND",
        "USAGE",
        "RATIONALE",
        "WARNING",
        "TASK"
    ]

    predicted_labels = [
        label_names[i]
        for i in range(len(prediction_row))
        if prediction_row[i] == 1
    ]

    # 6. QUALITY AUDIT INTERPRETATION


    if prediction_row[6] == 1:
        quality_rating = "BAD: Technical Debt"

    elif (
        prediction_row[5] == 1 or
        prediction_row[1] == 1 or
        prediction_row[2] == 1
    ):
        quality_rating = "QUESTIONABLE: High-Risk"

    elif (
        prediction_row[0] == 1 or
        prediction_row[3] == 1 or
        prediction_row[4] == 1
    ):
        quality_rating = "GOOD: Informative"

    else:
        quality_rating = "UNCATEGORIZED"


    # 7. FINAL OUTPUT

    print("\n========== CODE AUDIT RESULTS ==========")

    print(f"\nInput Comment:\n{raw_comment}")

    print("\nPredicted Categories:")

    if predicted_labels:
        for label in predicted_labels:
            print(f"- {label}")
    else:
        print("- NONE DETECTED")

    print(f"\nAudit Interpretation: {quality_rating}")

    print("\n========================================")

# Test 1
audit_code_comment(
    "This function calculates the total salary for all employees."
)

# Test 2
audit_code_comment(
    " * @author crazybob@google.com (Bob Lee)"
)

# Test 3
audit_code_comment(
    "but mandatory."
)

# Test 4
audit_code_comment(
    "p would be flagged as having called @code sqrt with an illegal argument."
)